import type {SidebarsConfig} from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  root: [
    { type: 'doc', id: 'docs' }
  ],

  bump: [{ type: 'autogenerated', dirName: 'bump' }],
  'guizhan-builds': [{ type: 'autogenerated', dirName: 'guizhan-builds' }],
  'infinity-expansion-2': [{ type: 'autogenerated', dirName: 'infinity-expansion-2' }],
  'slimefun-translation': [{ type: 'autogenerated', dirName: 'slimefun-translation' }]
}

export default sidebars
